{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 38993,
          "sha512": "9490c4deae31328a09e0117ebd360def30cad08581959c5c33615829011cbd0156d603a26f6b7f602d46dbfd97abe49f8d40bf04f8d47729fc643e4fe29aeb72",
          "sha256": "d9ec737e3f5d8019bd6a6b3ea77b48c7da3e3ddbc1f4fcd25ffd172c94817225",
          "sha1": "b0adadf1fe8e08fa4d992aaa8e14a6c9caab88e5",
          "md5": "e5c5f525770f6043b2ff225184551de0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 38993,
          "sha512": "9490c4deae31328a09e0117ebd360def30cad08581959c5c33615829011cbd0156d603a26f6b7f602d46dbfd97abe49f8d40bf04f8d47729fc643e4fe29aeb72",
          "sha256": "d9ec737e3f5d8019bd6a6b3ea77b48c7da3e3ddbc1f4fcd25ffd172c94817225",
          "sha1": "b0adadf1fe8e08fa4d992aaa8e14a6c9caab88e5",
          "md5": "e5c5f525770f6043b2ff225184551de0"
        }
      ]
    }
  ]
}
