{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 39674,
          "sha512": "19b60169b7c94882a125da2f0847b30b534857656a9c5ac45b475a29e06c5a17e8103b533d3cc5b78259b5349647df8bc7a7b0f9665b36b7e08cecc40f67c017",
          "sha256": "5bfb7ee42391693f6f3a98f8efb1430b7a2ba74b18653f24152d4ef5623d832b",
          "sha1": "b1adcf6dbcaaebba60b785486a0a7de7ed08528d",
          "md5": "738b2f9f2283cf67e8ea559e0ec96483"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 39674,
          "sha512": "19b60169b7c94882a125da2f0847b30b534857656a9c5ac45b475a29e06c5a17e8103b533d3cc5b78259b5349647df8bc7a7b0f9665b36b7e08cecc40f67c017",
          "sha256": "5bfb7ee42391693f6f3a98f8efb1430b7a2ba74b18653f24152d4ef5623d832b",
          "sha1": "b1adcf6dbcaaebba60b785486a0a7de7ed08528d",
          "md5": "738b2f9f2283cf67e8ea559e0ec96483"
        }
      ]
    }
  ]
}
