{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 52001,
          "sha512": "2432e3d690ad8e3d0593bd3ca6712920809ad1f9572d67b4dc89e2c8b2e893ae23750ccc28871371745f8e3c45b9dc5bfedaef20197f6657d9034b47d25cafaa",
          "sha256": "a9b627cb651fc9b0fc918e79d874cdc0ad7013a0c45943f1241b75630b50c1d1",
          "sha1": "7f6b77163798f556f525afdf3aa4c769687c3f03",
          "md5": "bf70d5d2e222dc072fa82fe5ab64a0aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 52001,
          "sha512": "2432e3d690ad8e3d0593bd3ca6712920809ad1f9572d67b4dc89e2c8b2e893ae23750ccc28871371745f8e3c45b9dc5bfedaef20197f6657d9034b47d25cafaa",
          "sha256": "a9b627cb651fc9b0fc918e79d874cdc0ad7013a0c45943f1241b75630b50c1d1",
          "sha1": "7f6b77163798f556f525afdf3aa4c769687c3f03",
          "md5": "bf70d5d2e222dc072fa82fe5ab64a0aa"
        }
      ]
    }
  ]
}
