{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-1.0.0.jar",
          "url": "processor-1.0.0.jar",
          "size": 35439,
          "sha512": "16a3c7743015f0f1b07b3e7bc2bb5c56286fde2f463f5a6ecf72626bc26b989e6c932ab8fa174537fd543ac06346094e3aec33db5ce508f737401bd47589d644",
          "sha256": "d541ece37e7d6cdab0ee279fb3d535ad2535a4bdca47591acad807dd264b3635",
          "sha1": "f0f8d36f57ee5ea350ec6fd06c226a69c8f8b68e",
          "md5": "8d12e10701bd4e489ff59232582a8b76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.hsbc.lab.arouter",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.0-rc7"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.69"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-1.0.0.jar",
          "url": "processor-1.0.0.jar",
          "size": 35439,
          "sha512": "16a3c7743015f0f1b07b3e7bc2bb5c56286fde2f463f5a6ecf72626bc26b989e6c932ab8fa174537fd543ac06346094e3aec33db5ce508f737401bd47589d644",
          "sha256": "d541ece37e7d6cdab0ee279fb3d535ad2535a4bdca47591acad807dd264b3635",
          "sha1": "f0f8d36f57ee5ea350ec6fd06c226a69c8f8b68e",
          "md5": "8d12e10701bd4e489ff59232582a8b76"
        }
      ]
    }
  ]
}
