{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-1.0.0.jar",
          "url": "processor-1.0.0.jar",
          "size": 37355,
          "sha512": "a9c93354d79cf184acfee8f00e7c43237986f8b9bf18411d3ccb3ce30f5c7ff554fc33270054afb2bb5d2ee8d2edd379ee61a916d0a8b34288d147895887630d",
          "sha256": "a9a148d64b184357a110d42e864cb7648c0335c33a001694d1f2f3a10362bdd8",
          "sha1": "07fca7a8051c3201dd193cc0d464bb6863e35f6b",
          "md5": "b2105030099e8062d2020fbabb95718f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.hsbc.lab.arouter",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.0-rc7"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.69"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-1.0.0.jar",
          "url": "processor-1.0.0.jar",
          "size": 37355,
          "sha512": "a9c93354d79cf184acfee8f00e7c43237986f8b9bf18411d3ccb3ce30f5c7ff554fc33270054afb2bb5d2ee8d2edd379ee61a916d0a8b34288d147895887630d",
          "sha256": "a9a148d64b184357a110d42e864cb7648c0335c33a001694d1f2f3a10362bdd8",
          "sha1": "07fca7a8051c3201dd193cc0d464bb6863e35f6b",
          "md5": "b2105030099e8062d2020fbabb95718f"
        }
      ]
    }
  ]
}
