{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-1.0.0.jar",
          "url": "processor-1.0.0.jar",
          "size": 37265,
          "sha512": "9925baa081270f735544114dc2ea8e8f3bd6cf50e1354fcecf69dded7c961eac9d71eb7eb5d80f7b2359650c64e05a5a8339dec9fc413021ed1692b8ea973349",
          "sha256": "acfa4f9ae9d4c13ef6e60a4d4d8d80cfa858668ffbc873af04c723ad2dbd65b5",
          "sha1": "597dfc03597a95cdafa09afbcc8b030155b9f088",
          "md5": "558e74a4aabdbd070cb33a767ef18848"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.hsbc.lab.arouter",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.0-rc7"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.69"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "processor-1.0.0.jar",
          "url": "processor-1.0.0.jar",
          "size": 37265,
          "sha512": "9925baa081270f735544114dc2ea8e8f3bd6cf50e1354fcecf69dded7c961eac9d71eb7eb5d80f7b2359650c64e05a5a8339dec9fc413021ed1692b8ea973349",
          "sha256": "acfa4f9ae9d4c13ef6e60a4d4d8d80cfa858668ffbc873af04c723ad2dbd65b5",
          "sha1": "597dfc03597a95cdafa09afbcc8b030155b9f088",
          "md5": "558e74a4aabdbd070cb33a767ef18848"
        }
      ]
    }
  ]
}
