{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 59156,
          "sha512": "3be595c1b700ccaa6679f284652c281e0626fe4648554c20b619f4c6afa5abee24281a2e0107c4c0dc17beba01981a5f19759b6ed29a929762212b4b6953cf9e",
          "sha256": "7caa7f5ca58c2a18cb2e3d5178afe7afa3f835ae55c90294f8bdd2ae79a82cef",
          "sha1": "d01cce299423ec00b834d7bf0ca365bca0ccfe50",
          "md5": "00b8cb62e832a2d9bf623abe653b0027"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.hsbc.lab.arouter",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 59156,
          "sha512": "3be595c1b700ccaa6679f284652c281e0626fe4648554c20b619f4c6afa5abee24281a2e0107c4c0dc17beba01981a5f19759b6ed29a929762212b4b6953cf9e",
          "sha256": "7caa7f5ca58c2a18cb2e3d5178afe7afa3f835ae55c90294f8bdd2ae79a82cef",
          "sha1": "d01cce299423ec00b834d7bf0ca365bca0ccfe50",
          "md5": "00b8cb62e832a2d9bf623abe653b0027"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-1.0.0-sources.jar",
          "url": "api-1.0.0-sources.jar",
          "size": 86529,
          "sha512": "63cd8ddb491086d819e37917b53af3b4310cb25b8613c824057705465daf0b9f96bb249a3156caad197c2a21f52ed3fc6b2709d9fabe03d8965d2de93b7e57ea",
          "sha256": "ac12691dce309bb7743424c42b564d42978dd553462a683fb835207833fc1da7",
          "sha1": "422eeaf8b0a3561a051452af75222222cfc8f810",
          "md5": "92abc031df8108783e3ece0ac4a4248e"
        }
      ]
    }
  ]
}
