{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 59957,
          "sha512": "d8b55a02af4b64e6ecc6a938963e680f255c4711f93821028618bd7b27a5a5b29e3f0291b6026b2853d8e774ab368a5cd62b787b7585d0f3721530ce0169e503",
          "sha256": "64d6c30902592e4b20841fa263878e5295a789c2597d8b33499ae876b475370d",
          "sha1": "aaeda4999a63625c891f18731d306463ed240047",
          "md5": "89f7a4cc1be915073eb682ad2bef0941"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.hsbc.lab.arouter",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 59957,
          "sha512": "d8b55a02af4b64e6ecc6a938963e680f255c4711f93821028618bd7b27a5a5b29e3f0291b6026b2853d8e774ab368a5cd62b787b7585d0f3721530ce0169e503",
          "sha256": "64d6c30902592e4b20841fa263878e5295a789c2597d8b33499ae876b475370d",
          "sha1": "aaeda4999a63625c891f18731d306463ed240047",
          "md5": "89f7a4cc1be915073eb682ad2bef0941"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-1.0.0-sources.jar",
          "url": "api-1.0.0-sources.jar",
          "size": 86475,
          "sha512": "149a55419748306f1ecb6733cff2c28c51faea870710a34dd9fde87647d6a5d300f95d2d20be86373f28f7bd97d5545996dd09e19b386568bc1e7f979bf77ccd",
          "sha256": "495ee38154ff0e36f673376049a7fcf4dd7d556298f4e66e0c4148236b225bca",
          "sha1": "2efa76a51ea6a40db530cc2d744303c685b9f59b",
          "md5": "e1c9bd6893b5d391de497a4da8f6c306"
        }
      ]
    }
  ]
}
