{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hsbc.lab.arouter",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 59141,
          "sha512": "ea06615aac1b3192072ea9cee91fed29a555d1dff721476fa76c1e08f21a7557ad418cf9f63b51ce09b3efbeb380ccae3d5f381d2f8c7f9646b7bfa3cfe5d301",
          "sha256": "b183bd1dc9d54e1c0c41e050bbb549651cc68a83c0eb479262fe2a62904873b1",
          "sha1": "3c061adbdd0df77c8a18dbbbc583d447c8436dc8",
          "md5": "4dcbeeaa1ef5510145df78f425832a9d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.hsbc.lab.arouter",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.aar",
          "url": "api-1.0.0.aar",
          "size": 59141,
          "sha512": "ea06615aac1b3192072ea9cee91fed29a555d1dff721476fa76c1e08f21a7557ad418cf9f63b51ce09b3efbeb380ccae3d5f381d2f8c7f9646b7bfa3cfe5d301",
          "sha256": "b183bd1dc9d54e1c0c41e050bbb549651cc68a83c0eb479262fe2a62904873b1",
          "sha1": "3c061adbdd0df77c8a18dbbbc583d447c8436dc8",
          "md5": "4dcbeeaa1ef5510145df78f425832a9d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "api-1.0.0-sources.jar",
          "url": "api-1.0.0-sources.jar",
          "size": 86503,
          "sha512": "d70d141be9b27a28370e907f53542a104b1e02c15975a84365b853c3784894ec75d33db5b38fdb1bb1ecd70fe9909547f6caa0941891143e737104e2e947de3f",
          "sha256": "8b3664d2214e403d80c6e8ebe4795b61e88f714e381faf8dfcccff640a93cbef",
          "sha1": "2ea46d82ca43c820a0cf3b62e1838333dfa59fc1",
          "md5": "3bc67021269dbe25f8b7d25f3fdba2de"
        }
      ]
    }
  ]
}
